### ISSUE TITLE
fails to build with ghc-9.6.3

### ISSUE THREAD

**Issue by juhp** [GaloisInc/cereal#109]
```
       /var/stackage/work/unpack-dir/unpacked/cereal-0.5.8.3-2d570ae699908d131b63fe176115809982f86ec4589cdbf42848aa2ca79209cb/tests/
GetTests.hs:79:12: error: [GHC-39999]
           • Could not deduce ‘Eq (Maybe a)’ arising from a use of ‘==’
             from the context: Eq a
               bound by the instance declaration at tests/GetTests.hs:78:10-25
           • In the first argument of ‘on’, namely ‘(==)’
             In the expression: (==) `on` either (const Nothing) Just . unR
             In an equation for ‘==’:
                 (==) = (==) `on` either (const Nothing) Just . unR
          |
       79 |   (==)  =  (==) `on` either (const Nothing) Just . unR 
          |            ^^^^
```

**Comment by glguy** [comment]
The tests run for me with current packages and `cabal test`. That error message certainly doesn't make much sense.

Isolating the code in the error message we get:

```haskell
module Demo where

import Data.Function

newtype R a =
  R { unR :: Either String a }
  deriving Show

-- Ignore equality of error message string
instance Eq a => Eq (R a) where
  (==)  =  (==) `on` either (const Nothing) Just . unR
```

and that loads in GHCi just fine.

Please reopen the ticket if you have a way to reproduce this, but it seems like a bug in the test environment.
