### ISSUE TITLE
Build failure with GHC 9.4

### ISSUE THREAD

**Issue by andreasabel** [GaloisInc/cereal#104]
```
$ cabal install -w ghc-9.4.0.20220523 cereal-0.5.8.2
...
Building library for cereal-0.5.8.2..
[1 of 4] Compiling Data.Serialize.Get ( src/Data/Serialize/Get.hs, dist/build/Data/Serialize/Get.o, dist/build/Data/Serialize/Get.dyn_o )

src/Data/Serialize/Get.hs:744:36: error:
    • Couldn't match expected type ‘Word64#’ with actual type ‘Word#’
    • In the first argument of ‘W64#’, namely
        ‘(w `uncheckedShiftL#` i)’
      In the expression: W64# (w `uncheckedShiftL#` i)
      In an equation for ‘shiftl_w64’:
          shiftl_w64 (W64# w) (I# i) = W64# (w `uncheckedShiftL#` i)
    |
744 | shiftl_w64 (W64# w) (I# i) = W64# (w `uncheckedShiftL#` i)
    |                                    ^^^^^^^^^^^^^^^
```
Error location:
https://github.com/GaloisInc/cereal/blob/b2ee49b1c3d50e5b226c4da0cb7811783ae71e94/src/Data/Serialize/Get.hs#L744

Reprise of:
- https://github.com/GaloisInc/cereal/issues/96

In my role as hackage trustee, I revised `cereal-0.5.8.2` with upper bound `base < 4.17` to exclude compilation with GHC 9.4:
- https://hackage.haskell.org/package/cereal-0.5.8.2/revisions/

A release (e.g. of 0.5.8.3) is warranted to comply with GHC 9.4.
- #103

**Comment by mpilgrem** [comment]
As GHC 9.4.1 is now [released](https://www.haskell.org/ghc/blog/20220807-ghc-9.4.1-released.html), I for one would be very pleased to see a version of `cereal` on Hackage that builds with GHC 9.4.1.

**Comment by andreasabel** [comment]
Ping @glguy.

**Comment by glguy** [comment]
Fixed in 0.5.8.3
